[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["cd frontend && npm install --production=false && npm run build && cd ../backend && npm install"]

[start]
cmd = "cd backend && node server.js"
